<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\IslandDestination;
use App\Models\City;

class IslandDestinationsSeeder extends Seeder
{
    public function run()
    {
        $internationals = [
            ['title_en' => 'Maldives Paradise Island', 'title_ar' => 'جزيرة المالديف الفردوس', 'description_en' => 'Experience luxury at its finest with crystal clear waters and pristine beaches.', 'description_ar' => 'اختبر الفخامة بأفضل صورها مع المياه الصافية والشواطئ النقية.', 'slug' => 'maldives-paradise', 'price' => 2500.00, 'rating' => 4.8, 'type' => 'international', 'image' => 'international/1.webp', 'duration_en' => '7 Days', 'duration_ar' => '٧ أيام', 'groupSize_en' => '2-4 People', 'groupSize_ar' => '٢-٤ أشخاص', 'location_en' => 'Maldives', 'location_ar' => 'المالديف', 'features' => json_encode(['Water Sports', 'Spa & Wellness', 'Fine Dining', 'Snorkeling']), 'active' => true],
            ['title_en' => 'Bali Island Escape', 'title_ar' => 'رحلة جزيرة بالي', 'description_en' => 'Discover the cultural richness and natural beauty of Bali with expert guides.', 'description_ar' => 'اكتشف الثروة الثقافية والجمال الطبيعي لبالي مع الأدلاء الخبراء.', 'slug' => 'bali-escape', 'price' => 1800.00, 'rating' => 4.7, 'type' => 'international', 'image' => 'international/2.webp', 'duration_en' => '5 Days', 'duration_ar' => '٥ أيام', 'groupSize_en' => '2-6 People', 'groupSize_ar' => '٢-٦ أشخاص', 'location_en' => 'Indonesia', 'location_ar' => 'إندونيسيا', 'features' => json_encode(['Temple Tours', 'Yoga Retreat', 'Beach Club', 'Cultural Immersion']), 'active' => true],
            ['title_en' => 'Seychelles Luxury Retreat', 'title_ar' => 'ملجأ سيشل الفاخر', 'description_en' => 'An exclusive tropical paradise with white sand beaches and turquoise lagoons.', 'description_ar' => 'جنة استوائية حصرية مع شواطئ رملية بيضاء وبحيرات فيروزية.', 'slug' => 'seychelles-luxury', 'price' => 3200.00, 'rating' => 4.9, 'type' => 'international', 'image' => 'international/3.webp', 'duration_en' => '8 Days', 'duration_ar' => '٨ أيام', 'groupSize_en' => '2-4 People', 'groupSize_ar' => '٢-٤ أشخاص', 'location_en' => 'Seychelles', 'location_ar' => 'سيشل', 'features' => json_encode(['Diving', 'Private Beach', 'Sunset Cruises', 'Wildlife Tours']), 'active' => true],
            ['title_en' => 'Fiji Island Adventure', 'title_ar' => 'مغامرة جزر فيجي', 'description_en' => 'Adventure and relaxation in tropical Fiji islands.', 'description_ar' => 'المغامرة والاسترخاء في جزر فيجي الاستوائية.', 'slug' => 'fiji-adventure', 'price' => 2200.00, 'rating' => 4.6, 'type' => 'international', 'image' => 'international/4.webp', 'duration_en' => '6 Days', 'duration_ar' => '٦ أيام', 'groupSize_en' => '2-5 People', 'groupSize_ar' => '٢-٥ أشخاص', 'location_en' => 'Fiji', 'location_ar' => 'فيجي', 'features' => json_encode(['Beach Resorts', 'Water Sports', 'Island Tours', 'Relaxation']), 'active' => true],
            ['title_en' => 'Hawaii Tropical Paradise', 'title_ar' => 'جنة هاواي الاستوائية', 'description_en' => 'Stunning beaches and volcanic landscapes in Hawaii.', 'description_ar' => 'شواطئ خلابة ومناظر بركانية في هاواي.', 'slug' => 'hawaii-paradise', 'price' => 3000.00, 'rating' => 4.8, 'type' => 'international', 'image' => 'international/5.webp', 'duration_en' => '7 Days', 'duration_ar' => '٧ أيام', 'groupSize_en' => '2-6 People', 'groupSize_ar' => '٢-٦ أشخاص', 'location_en' => 'Hawaii', 'location_ar' => 'هاواي', 'features' => json_encode(['Volcanic Tours', 'Beach Resorts', 'Surfing', 'Snorkeling']), 'active' => true],
            ['title_en' => 'Thailand Beach Getaway', 'title_ar' => 'رحلة شاطئ تايلاند', 'description_en' => 'Experience Thai culture and beautiful beaches.', 'description_ar' => 'اختبر الثقافة التايلاندية والشواطئ الجميلة.', 'slug' => 'thailand-getaway', 'price' => 1600.00, 'rating' => 4.7, 'type' => 'international', 'image' => 'international/6.webp', 'duration_en' => '5 Days', 'duration_ar' => '٥ أيام', 'groupSize_en' => '2-8 People', 'groupSize_ar' => '٢-٨ أشخاص', 'location_en' => 'Thailand', 'location_ar' => 'تايلاند', 'features' => json_encode(['Temple Tours', 'Beach Resorts', 'Local Cuisine', 'Island Hopping']), 'active' => true],
            ['title_en' => 'Mauritius Escape', 'title_ar' => 'رحلة موريشيوس', 'description_en' => 'Pristine beaches and cultural diversity in Mauritius.', 'description_ar' => 'شواطئ نقية وتنوع ثقافي في موريشيوس.', 'slug' => 'mauritius-escape', 'price' => 2400.00, 'rating' => 4.7, 'type' => 'international', 'image' => 'international/7.webp', 'duration_en' => '6 Days', 'duration_ar' => '٦ أيام', 'groupSize_en' => '2-4 People', 'groupSize_ar' => '٢-٤ أشخاص', 'location_en' => 'Mauritius', 'location_ar' => 'موريشيوس', 'features' => json_encode(['Beach Resorts', 'Water Sports', 'Cultural Tours', 'Fine Dining']), 'active' => true],
            ['title_en' => 'Bora Bora Island Tour', 'title_ar' => 'جولة جزيرة بورا بورا', 'description_en' => 'Overwater bungalows and crystal clear lagoons.', 'description_ar' => 'أكواخ فوق الماء وبحيرات صافية.', 'slug' => 'bora-bora-tour', 'price' => 3500.00, 'rating' => 4.9, 'type' => 'international', 'image' => 'international/8.webp', 'duration_en' => '7 Days', 'duration_ar' => '٧ أيام', 'groupSize_en' => '2-4 People', 'groupSize_ar' => '٢-٤ أشخاص', 'location_en' => 'French Polynesia', 'location_ar' => 'بولينيزيا الفرنسية', 'features' => json_encode(['Overwater Bungalows', 'Lagoon Activities', 'Snorkeling', 'Romance']), 'active' => true],
            ['title_en' => 'Caribbean Cruise Dream', 'title_ar' => 'رحلة حلم البحر الكاريبي', 'description_en' => 'Island hopping adventure in the Caribbean.', 'description_ar' => 'مغامرة القفز بين الجزر في البحر الكاريبي.', 'slug' => 'caribbean-cruise', 'price' => 2800.00, 'rating' => 4.6, 'type' => 'international', 'image' => 'international/9.webp', 'duration_en' => '8 Days', 'duration_ar' => '٨ أيام', 'groupSize_en' => '4-10 People', 'groupSize_ar' => '٤-١٠ أشخاص', 'location_en' => 'Caribbean', 'location_ar' => 'البحر الكاريبي', 'features' => json_encode(['Island Hopping', 'Beach Resorts', 'Water Sports', 'Cruise']), 'active' => true],
            ['title_en' => 'Palau Island Discovery', 'title_ar' => 'اكتشاف جزيرة بالاو', 'description_en' => 'World-class diving and pristine marine life.', 'description_ar' => 'الغوص من الدرجة الأولى والحياة البحرية النقية.', 'slug' => 'palau-discovery', 'price' => 2600.00, 'rating' => 4.8, 'type' => 'international', 'image' => 'international/10.webp', 'duration_en' => '6 Days', 'duration_ar' => '٦ أيام', 'groupSize_en' => '2-6 People', 'groupSize_ar' => '٢-٦ أشخاص', 'location_en' => 'Palau', 'location_ar' => 'بالاو', 'features' => json_encode(['World-Class Diving', 'Jellyfish Lake', 'Marine Life', 'Adventures']), 'active' => true],
            ['title_en' => 'Santorini Greece Escape', 'title_ar' => 'رحلة سانتوريني اليونان', 'description_en' => 'White-washed buildings and stunning Mediterranean views.', 'description_ar' => 'مباني بيضاء ومناظر متوسطة خلابة.', 'slug' => 'santorini-escape', 'price' => 2000.00, 'rating' => 4.9, 'type' => 'international', 'image' => 'international/11.webp', 'duration_en' => '5 Days', 'duration_ar' => '٥ أيام', 'groupSize_en' => '2-4 People', 'groupSize_ar' => '٢-٤ أشخاص', 'location_en' => 'Greece', 'location_ar' => 'اليونان', 'features' => json_encode(['Romantic Views', 'Beach Resorts', 'Local Wine', 'Sunset Views']), 'active' => true],
            ['title_en' => 'Maldives Water Bungalow', 'title_ar' => 'أكواخ المالديف المائية', 'description_en' => 'Exclusive water villas and underwater dining.', 'description_ar' => 'فيلات مائية حصرية وتناول طعام تحت الماء.', 'slug' => 'maldives-bungalow', 'price' => 4000.00, 'rating' => 5.0, 'type' => 'international', 'image' => 'international/12.webp', 'duration_en' => '7 Days', 'duration_ar' => '٧ أيام', 'groupSize_en' => '2-3 People', 'groupSize_ar' => '٢-٣ أشخاص', 'location_en' => 'Maldives', 'location_ar' => 'المالديف', 'features' => json_encode(['Water Villas', 'Underwater Dining', 'Luxury', 'Exclusive']), 'active' => true],
            ['title_en' => 'Maldives Resort Retreat', 'title_ar' => 'ملجأ منتجع المالديف', 'description_en' => 'All-inclusive tropical island resort experience.', 'description_ar' => 'تجربة منتجع جزيرة استوائية شاملة.', 'slug' => 'maldives-resort', 'price' => 2700.00, 'rating' => 4.8, 'type' => 'international', 'image' => 'international/13.webp', 'duration_en' => '6 Days', 'duration_ar' => '٦ أيام', 'groupSize_en' => '2-8 People', 'groupSize_ar' => '٢-٨ أشخاص', 'location_en' => 'Maldives', 'location_ar' => 'المالديف', 'features' => json_encode(['All-Inclusive', 'Beach Resorts', 'Water Sports', 'Dining']), 'active' => true],
            ['title_en' => 'Bali Beach Bliss', 'title_ar' => 'نعيم شاطئ بالي', 'description_en' => 'Tropical beaches and ancient temple exploration.', 'description_ar' => 'شواطئ استوائية واستكشاف المعابد القديمة.', 'slug' => 'bali-bliss', 'price' => 1500.00, 'rating' => 4.6, 'type' => 'international', 'image' => 'international/14.webp', 'duration_en' => '5 Days', 'duration_ar' => '٥ أيام', 'groupSize_en' => '2-6 People', 'groupSize_ar' => '٢-٦ أشخاص', 'location_en' => 'Indonesia', 'location_ar' => 'إندونيسيا', 'features' => json_encode(['Temple Tours', 'Beach Resorts', 'Local Culture', 'Yoga']), 'active' => true],
            ['title_en' => 'Aruba Island Adventure', 'title_ar' => 'مغامرة جزيرة أروبا', 'description_en' => 'Sunny beaches and water sports paradise.', 'description_ar' => 'شواطئ مشمسة وجنة الألعاب المائية.', 'slug' => 'aruba-adventure', 'price' => 1900.00, 'rating' => 4.7, 'type' => 'international', 'image' => 'international/15.webp', 'duration_en' => '5 Days', 'duration_ar' => '٥ أيام', 'groupSize_en' => '2-6 People', 'groupSize_ar' => '٢-٦ أشخاص', 'location_en' => 'Aruba', 'location_ar' => 'أروبا', 'features' => json_encode(['Sunny Beaches', 'Water Sports', 'Windsurfing', 'Relaxation']), 'active' => true],
            ['title_en' => 'Zanzibar Spice Island', 'title_ar' => 'جزيرة زنجبار الفاخرة', 'description_en' => 'Historic spice island with swahili culture.', 'description_ar' => 'جزيرة تاريخية بثقافة سواحيلية.', 'slug' => 'zanzibar-spice', 'price' => 2100.00, 'rating' => 4.5, 'type' => 'international', 'image' => 'international/16.webp', 'duration_en' => '6 Days', 'duration_ar' => '٦ أيام', 'groupSize_en' => '2-5 People', 'groupSize_ar' => '٢-٥ أشخاص', 'location_en' => 'Tanzania', 'location_ar' => 'تنزانيا', 'features' => json_encode(['Historic Sites', 'Beach Resorts', 'Local Culture', 'Spice Tours']), 'active' => true],
        ];

        foreach ($internationals as $data) {
            $attributes = ['slug' => $data['slug']];
            IslandDestination::updateOrCreate($attributes, $data);
        }
    }
}
