<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\VisaCountry;

class VisaCountriesTableSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                "name_en" => "USA",
                "name_ar" => "الولايات المتحدة",
                "name_zh" => "美国",
                "slug" => "usa",
                "flagEmoji" => "🇺🇸",
                "flagPath" => "/flags/USA.jpg",
                "visaInfo" => [
                    "visaType_en" => "B1/B2 Tourist or Business",
                    "visaType_ar" => "تأشيرة سياحية أو عمل B1/B2",
                    "visaType_zh" => "B1/B2 旅游或商务签证",
                    "processingTime_en" => "5-7 business days",
                    "processingTime_ar" => "٥-٧ أيام عمل",
                    "processingTime_zh" => "5-7个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "US visa applications require passport copy, photo, proof of funds, and invitation or travel details.",
                    "description_ar" => "تتطلب طلبات التأشيرة الأمريكية نسخة من جواز السفر، صورة شخصية، إثبات مالي، وتفاصيل الدعوة أو السفر.",
                    "description_zh" => "美国签证申请需要护照复印件、照片、资金证明以及邀请函或旅行详情。",
                ],
            ],
            [
                "name_en" => "UK",
                "name_ar" => "المملكة المتحدة",
                "name_zh" => "英国",
                "slug" => "uk",
                "flagEmoji" => "🇬🇧",
                "flagPath" => "/flags/UK.jpg",
                "visaInfo" => [
                    "visaType_en" => "Standard Visitor Visa",
                    "visaType_ar" => "تأشيرة الزائر القياسية",
                    "visaType_zh" => "标准访客签证",
                    "processingTime_en" => "4-6 business days",
                    "processingTime_ar" => "٤-٦ أيام عمل",
                    "processingTime_zh" => "4-6个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "UK visitor visas need passport copy, photo, hotel booking, and proof of finances.",
                    "description_ar" => "تتطلب تأشيرات الزائر للمملكة المتحدة نسخة جواز سفر، صورة شخصية، حجز فندق، وإثبات مالي.",
                    "description_zh" => "英国访客签证需要护照复印件、照片、酒店预订和资金证明。",
                ],
            ],
            [
                "name_en" => "India",
                "name_ar" => "الهند",
                "name_zh" => "印度",
                "slug" => "india",
                "flagEmoji" => "🇮🇳",
                "flagPath" => "/flags/india.jpg",
                "visaInfo" => [
                    "visaType_en" => "e-Visa / Tourist",
                    "visaType_ar" => "تأشيرة إلكترونية / سياحية",
                    "visaType_zh" => "电子签证/旅游签证",
                    "processingTime_en" => "3-5 business days",
                    "processingTime_ar" => "٣-٥ أيام عمل",
                    "processingTime_zh" => "3-5个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "India e-Visa requires a passport scan, photo, and travel itinerary details.",
                    "description_ar" => "تتطلب التأشيرة الإلكترونية للهند مسح جواز السفر، صورة شخصية، وتفاصيل خطط السفر.",
                    "description_zh" => "印度电子签证需要护照扫描件、照片和旅行行程详情。",
                ],
            ],
            [
                "name_en" => "Japan",
                "name_ar" => "اليابان",
                "name_zh" => "日本",
                "slug" => "japan",
                "flagEmoji" => "🇯🇵",
                "flagPath" => "/flags/japan.jpg",
                "visaInfo" => [
                    "visaType_en" => "Tourist / Short-term Business",
                    "visaType_ar" => "سياحية / أعمال قصيرة المدى",
                    "visaType_zh" => "旅游/短期商务签证",
                    "processingTime_en" => "5-8 business days",
                    "processingTime_ar" => "٥-٨ أيام عمل",
                    "processingTime_zh" => "5-8个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Japanese visa applications are reviewed at the consulate after submitting passport and travel details.",
                    "description_ar" => "تتم مراجعة طلبات التأشيرة اليابانية في القنصلية بعد تقديم جواز السفر وتفاصيل السفر.",
                    "description_zh" => "日本签证申请在提交护照和旅行详情后由领事馆审核。",
                ],
            ],
            [
                "name_en" => "Ireland",
                "name_ar" => "أيرلندا",
                "name_zh" => "爱尔兰",
                "slug" => "ireland",
                "flagEmoji" => "🇮🇪",
                "flagPath" => "/flags/ireland.jpg",
                "visaInfo" => [
                    "visaType_en" => "Short Stay Visa",
                    "visaType_ar" => "تأشيرة إقامة قصيرة",
                    "visaType_zh" => "短期停留签证",
                    "processingTime_en" => "6-8 business days",
                    "processingTime_ar" => "٦-٨ أيام عمل",
                    "processingTime_zh" => "6-8个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Ireland visitor visas require a passport scan, photos, invitation letter or booking confirmation.",
                    "description_ar" => "تتطلب تأشيرات الزوار لأيرلندا مسح جواز السفر، صور شخصية، خطاب دعوة أو تأكيد الحجز.",
                    "description_zh" => "爱尔兰访客签证需要护照扫描件、照片、邀请函或预订确认信。",
                ],
            ],
            [
                "name_en" => "Australia",
                "name_ar" => "أستراليا",
                "name_zh" => "澳大利亚",
                "slug" => "australia",
                "flagEmoji" => "🇦🇺",
                "flagPath" => "/flags/Asralia.jpg",
                "visaInfo" => [
                    "visaType_en" => "eVisitor / Tourist",
                    "visaType_ar" => "تأشيرة إلكترونية / سياحية",
                    "visaType_zh" => "电子访客签证/旅游签证",
                    "processingTime_en" => "3-5 business days",
                    "processingTime_ar" => "٣-٥ أيام عمل",
                    "processingTime_zh" => "3-5个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Australian visitor visas need passport details, photo, and proof of funds.",
                    "description_ar" => "تتطلب تأشيرات الزوار الأسترالية تفاصيل جواز السفر، صورة شخصية، وإثبات مالي.",
                    "description_zh" => "澳大利亚访客签证需要护照详细信息、照片和资金证明。",
                ],
            ],
            [
                "name_en" => "Azerbaijan",
                "name_ar" => "أذربيجان",
                "name_zh" => "阿塞拜疆",
                "slug" => "azerbaijan",
                "flagEmoji" => "🇦🇿",
                "flagPath" => "/flags/azrabigan.jpg",
                "visaInfo" => [
                    "visaType_en" => "E-Visa",
                    "visaType_ar" => "تأشيرة إلكترونية",
                    "visaType_zh" => "电子签证",
                    "processingTime_en" => "2-4 business days",
                    "processingTime_ar" => "٢-٤ أيام عمل",
                    "processingTime_zh" => "2-4个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Azerbaijan e-Visa requires passport copy, photo and travel itinerary details.",
                    "description_ar" => "تتطلب التأشيرة الإلكترونية لأذربيجان نسخة جواز السفر، صورة شخصية وتفاصيل خطط السفر.",
                    "description_zh" => "阿塞拜疆电子签证需要护照复印件、照片和旅行行程详情。",
                ],
            ],
            [
                "name_en" => "Ethiopia",
                "name_ar" => "إثيوبيا",
                "name_zh" => "埃塞俄比亚",
                "slug" => "ethiopia",
                "flagEmoji" => "🇪🇹",
                "flagPath" => "/flags/athubia.jpg",
                "visaInfo" => [
                    "visaType_en" => "Tourist / Business",
                    "visaType_ar" => "سياحية / أعمال",
                    "visaType_zh" => "旅游/商务签证",
                    "processingTime_en" => "5-7 business days",
                    "processingTime_ar" => "٥-٧ أيام عمل",
                    "processingTime_zh" => "5-7个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Ethiopia visa requests require passport copy, photo, hotel or itinerary, and proof of funds.",
                    "description_ar" => "تتطلب طلبات التأشيرة لإثيوبيا نسخة جواز السفر، صورة شخصية، فندق أو خطط سفر، وإثبات مالي.",
                    "description_zh" => "埃塞俄比亚签证申请需要护照复印件、照片、酒店或行程单以及资金证明。",
                ],
            ],
            [
                "name_en" => "Italy",
                "name_ar" => "إيطاليا",
                "name_zh" => "意大利",
                "slug" => "italy",
                "flagEmoji" => "🇮🇹",
                "flagPath" => null,
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Italy Schengen visas require passport, photo, travel insurance, accommodation details and bank statement.",
                    "description_ar" => "تتطلب تأشيرات شنغن لإيطاليا جواز سفر، صورة شخصية، تأمين سفر، تفاصيل الإقامة وكشف حساب بنكي.",
                    "description_zh" => "意大利申根签证需要护照、照片、旅行保险、住宿详情和银行对账单。",
                ],
            ],
            [
                "name_en" => "Thailand - Electronic",
                "name_ar" => "تايلاند - إلكترونية",
                "name_zh" => "泰国 - 电子签证",
                "slug" => "thailand-electronic",
                "flagEmoji" => "🇹🇭",
                "flagPath" => "/flags/thailnad.jpg",
                "visaInfo" => [
                    "visaType_en" => "eVisa / Tourist",
                    "visaType_ar" => "تأشيرة إلكترونية / سياحية",
                    "visaType_zh" => "电子签证/旅游签证",
                    "processingTime_en" => "2-4 business days",
                    "processingTime_ar" => "٢-٤ أيام عمل",
                    "processingTime_zh" => "2-4个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Thailand eVisa requires passport copy, photo, arrival details, and proof of funds.",
                    "description_ar" => "تتطلب التأشيرة الإلكترونية لتايلاند نسخة جواز السفر، صورة شخصية، تفاصيل الوصول، وإثبات مالي.",
                    "description_zh" => "泰国电子签证需要护照复印件、照片、入境详情和资金证明。",
                ],
            ],
            [
                "name_en" => "Electronic Russia",
                "name_ar" => "روسيا الإلكترونية",
                "name_zh" => "俄罗斯电子签证",
                "slug" => "electronic-russia",
                "flagEmoji" => "🇷🇺",
                "flagPath" => "/flags/rusha.jpg",
                "visaInfo" => [
                    "visaType_en" => "Russian eVisa",
                    "visaType_ar" => "تأشيرة روسيا الإلكترونية",
                    "visaType_zh" => "俄罗斯电子签证",
                    "processingTime_en" => "3-6 business days",
                    "processingTime_ar" => "٣-٦ أيام عمل",
                    "processingTime_zh" => "3-6个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Russian eVisa requires passport information, photo, travel itinerary and hotel details.",
                    "description_ar" => "تتطلب التأشيرة الإلكترونية الروسية معلومات جواز السفر، صورة شخصية، خطط السفر وتفاصيل الفندق.",
                    "description_zh" => "俄罗斯电子签证需要护照信息、照片、旅行行程和酒店详情。",
                ],
            ],
            [
                "name_en" => "Tanzania",
                "name_ar" => "تنزانيا",
                "name_zh" => "坦桑尼亚",
                "slug" => "tanzania",
                "flagEmoji" => "🇹🇿",
                "flagPath" => "/flags/tanzania.jpg",
                "visaInfo" => [
                    "visaType_en" => "eVisa / Tourist",
                    "visaType_ar" => "تأشيرة إلكترونية / سياحية",
                    "visaType_zh" => "电子签证/旅游签证",
                    "processingTime_en" => "2-4 business days",
                    "processingTime_ar" => "٢-٤ أيام عمل",
                    "processingTime_zh" => "2-4个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Tanzania eVisa requires passport copy, photo, travel plans, and hotel or safari booking details.",
                    "description_ar" => "تتطلب التأشيرة الإلكترونية لتنزانيا نسخة جواز السفر، صورة شخصية، خطط السفر، وتفاصيل حجز الفندق أو السفاري.",
                    "description_zh" => "坦桑尼亚电子签证需要护照复印件、照片、旅行计划以及酒店或野生动物园预订详情。",
                ],
            ],
            [
                "name_en" => "Dubai",
                "name_ar" => "دبي",
                "name_zh" => "迪拜",
                "slug" => "dubai",
                "flagEmoji" => "🇦🇪",
                "flagPath" => "/flags/Dubai.jpg",
                "visaInfo" => [
                    "visaType_en" => "UAE Tourist Visa",
                    "visaType_ar" => "تأشيرة سياحية للإمارات",
                    "visaType_zh" => "阿联酋旅游签证",
                    "processingTime_en" => "2-5 business days",
                    "processingTime_ar" => "٢-٥ أيام عمل",
                    "processingTime_zh" => "2-5个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Dubai visa applications need passport copy, photo, hotel booking, and return flight details.",
                    "description_ar" => "تتطلب طلبات تأشيرة دبي نسخة جواز السفر، صورة شخصية، حجز فندق، وتفاصيل رحلة العودة.",
                    "description_zh" => "迪拜签证申请需要护照复印件、照片、酒店预订和返程航班详情。",
                ],
            ],
            [
                "name_en" => "UK - Electronic",
                "name_ar" => "المملكة المتحدة - إلكترونية",
                "name_zh" => "英国 - 电子签证",
                "slug" => "uk-electronic",
                "flagEmoji" => "🇬🇧",
                "flagPath" => "/flags/UK.jpg",
                "visaInfo" => [
                    "visaType_en" => "Electronic Visitor Visa",
                    "visaType_ar" => "تأشيرة زائر إلكترونية",
                    "visaType_zh" => "电子访客签证",
                    "processingTime_en" => "4-6 business days",
                    "processingTime_ar" => "٤-٦ أيام عمل",
                    "processingTime_zh" => "4-6个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "UK electronic visas require passport copy, photo, and travel itinerary.",
                    "description_ar" => "تتطلب التأشيرات الإلكترونية للمملكة المتحدة نسخة جواز السفر، صورة شخصية، وخطة السفر.",
                    "description_zh" => "英国电子签证需要护照复印件、照片和旅行行程。",
                ],
            ],
            [
                "name_en" => "Uzbekistan - Electronic",
                "name_ar" => "أوزبكستان - إلكترونية",
                "name_zh" => "乌兹别克斯坦 - 电子签证",
                "slug" => "uzbekistan-electronic",
                "flagEmoji" => "🇺🇿",
                "flagPath" => "/flags/Flag_of_Uzbekistan.jpg",
                "visaInfo" => [
                    "visaType_en" => "Uzbekistan eVisa",
                    "visaType_ar" => "تأشيرة أوزبكستان الإلكترونية",
                    "visaType_zh" => "乌兹别克斯坦电子签证",
                    "processingTime_en" => "3-5 business days",
                    "processingTime_ar" => "٣-٥ أيام عمل",
                    "processingTime_zh" => "3-5个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Uzbekistan eVisa requires passport copy, photo and travel itinerary.",
                    "description_ar" => "تتطلب التأشيرة الإلكترونية لأوزبكستان نسخة جواز السفر، صورة شخصية وخطة السفر.",
                    "description_zh" => "乌兹别克斯坦电子签证需要护照复印件、照片和旅行行程。",
                ],
            ],
            [
                "name_en" => "Germany",
                "name_ar" => "ألمانيا",
                "name_zh" => "德国",
                "slug" => "germany",
                "flagEmoji" => "🇩🇪",
                "flagPath" => "/flags/Flag_of_Germany.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Germany Schengen visa requires passport, photos, travel insurance, accommodation and bank proof.",
                    "description_ar" => "تتطلب تأشيرة شنغن لألمانيا جواز سفر، صور شخصية، تأمين سفر، إقامة وإثبات بنكي.",
                    "description_zh" => "德国申根签证需要护照、照片、旅行保险、住宿和银行证明。",
                ],
            ],
            [
                "name_en" => "Spain",
                "name_ar" => "إسبانيا",
                "name_zh" => "西班牙",
                "slug" => "spain",
                "flagEmoji" => "🇪🇸",
                "flagPath" => "/flags/Flag_of_Spain.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Spain Schengen visas require passport, photo, travel insurance, accommodation and financial proof.",
                    "description_ar" => "تتطلب تأشيرات شنغن لإسبانيا جواز سفر، صورة شخصية، تأمين سفر، إقامة وإثبات مالي.",
                    "description_zh" => "西班牙申根签证需要护照、照片、旅行保险、住宿和资金证明。",
                ],
            ],
            [
                "name_en" => "France",
                "name_ar" => "فرنسا",
                "name_zh" => "法国",
                "slug" => "france",
                "flagEmoji" => "🇫🇷",
                "flagPath" => "/flags/France-Flag.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "France visitor visas require passport, photo, travel insurance, hotel reservation and bank statements.",
                    "description_ar" => "تتطلب تأشيرات الزوار لفرنسا جواز سفر، صورة شخصية، تأمين سفر، حجز فندق وكشوفات بنكية.",
                    "description_zh" => "法国访客签证需要护照、照片、旅行保险、酒店预订和银行对账单。",
                ],
            ],
            [
                "name_en" => "Netherlands",
                "name_ar" => "هولندا",
                "name_zh" => "荷兰",
                "slug" => "netherlands",
                "flagEmoji" => "🇳🇱",
                "flagPath" => "/flags/Netherlands-Flag.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Netherlands Schengen visas require passport, photo, travel insurance, accommodation and bank proof.",
                    "description_ar" => "تتطلب تأشيرات شنغن لهولندا جواز سفر، صورة شخصية، تأمين سفر، إقامة وإثبات بنكي.",
                    "description_zh" => "荷兰申根签证需要护照、照片、旅行保险、住宿和银行证明。",
                ],
            ],
            [
                "name_en" => "Portugal",
                "name_ar" => "البرتغال",
                "name_zh" => "葡萄牙",
                "slug" => "portugal",
                "flagEmoji" => "🇵🇹",
                "flagPath" => "/flags/Portugal-Flag.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Portugal Schengen visas require passport, photo, travel insurance, accommodation confirmation and financial proof.",
                    "description_ar" => "تتطلب تأشيرات شنغن للبرتغال جواز سفر، صورة شخصية، تأمين سفر، تأكيد الإقامة وإثبات مالي.",
                    "description_zh" => "葡萄牙申根签证需要护照、照片、旅行保险、住宿确认和资金证明。",
                ],
            ],
            [
                "name_en" => "Sweden",
                "name_ar" => "السويد",
                "name_zh" => "瑞典",
                "slug" => "sweden",
                "flagEmoji" => "🇸🇪",
                "flagPath" => "/flags/Sweden-Flag.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Sweden Schengen visas need passport, photo, travel insurance, accommodation and bank statement.",
                    "description_ar" => "تتطلب تأشيرات شنغن للسويد جواز سفر، صورة شخصية، تأمين سفر، إقامة وكشف حساب بنكي.",
                    "description_zh" => "瑞典申根签证需要护照、照片、旅行保险、住宿和银行对账单。",
                ],
            ],
            [
                "name_en" => "Czechia",
                "name_ar" => "التشيك",
                "name_zh" => "捷克",
                "slug" => "czechia",
                "flagEmoji" => "🇨🇿",
                "flagPath" => "/flags/Czechia-Flag.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Czechia Schengen visas require passport, photos, travel insurance, hotel booking and proof of finances.",
                    "description_ar" => "تتطلب تأشيرات شنغن للتشيك جواز سفر، صور شخصية، تأمين سفر، حجز فندق وإثبات مالي.",
                    "description_zh" => "捷克申根签证需要护照、照片、旅行保险、酒店预订和资金证明。",
                ],
            ],
            [
                "name_en" => "Greece",
                "name_ar" => "اليونان",
                "name_zh" => "希腊",
                "slug" => "greece",
                "flagEmoji" => "🇬🇷",
                "flagPath" => "/flags/Greece-Flag.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Greece Schengen visa applications require passport, photo, travel insurance, accommodation and bank proof.",
                    "description_ar" => "تتطلب طلبات تأشيرة شنغن لليونان جواز سفر، صورة شخصية، تأمين سفر، إقامة وإثبات بنكي.",
                    "description_zh" => "希腊申根签证申请需要护照、照片、旅行保险、住宿和银行证明。",
                ],
            ],
            [
                "name_en" => "Hungary",
                "name_ar" => "المجر",
                "name_zh" => "匈牙利",
                "slug" => "hungary",
                "flagEmoji" => "🇭🇺",
                "flagPath" => "/flags/Hungary-Flag.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Hungary Schengen visas require passport, photo, travel insurance, accommodation and bank statements.",
                    "description_ar" => "تتطلب تأشيرات شنغن للمجر جواز سفر، صورة شخصية، تأمين سفر، إقامة وكشوفات بنكية.",
                    "description_zh" => "匈牙利申根签证需要护照、照片、旅行保险、住宿和银行对账单。",
                ],
            ],
            [
                "name_en" => "Belgium",
                "name_ar" => "بلجيكا",
                "name_zh" => "比利时",
                "slug" => "belgium",
                "flagEmoji" => "🇧🇪",
                "flagPath" => "/flags/Belgium-Flag.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Belgium Schengen visas require passport, photos, travel insurance, hotel booking and proof of funds.",
                    "description_ar" => "تتطلب تأشيرات شنغن لبلجيكا جواز سفر، صور شخصية، تأمين سفر، حجز فندق وإثبات أموال.",
                    "description_zh" => "比利时申根签证需要护照、照片、旅行保险、酒店预订和资金证明。",
                ],
            ],
            [
                "name_en" => "Switzerland",
                "name_ar" => "سويسرا",
                "name_zh" => "瑞士",
                "slug" => "switzerland",
                "flagEmoji" => "🇨🇭",
                "flagPath" => "/flags/Switzerland-Flag.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Switzerland Schengen visas require passport, photo, travel insurance, accommodation and bank proof.",
                    "description_ar" => "تتطلب تأشيرات شنغن لسويسرا جواز سفر، صورة شخصية، تأمين سفر، إقامة وإثبات بنكي.",
                    "description_zh" => "瑞士申根签证需要护照、照片、旅行保险、住宿和银行证明。",
                ],
            ],
            [
                "name_en" => "Austria",
                "name_ar" => "النمسا",
                "name_zh" => "奥地利",
                "slug" => "austria",
                "flagEmoji" => "🇦🇹",
                "flagPath" => "/flags/Austria-Flag.jpg",
                "visaInfo" => [
                    "visaType_en" => "Schengen Visitor Visa",
                    "visaType_ar" => "تأشيرة شنغن للزوار",
                    "visaType_zh" => "申根访客签证",
                    "processingTime_en" => "7-10 business days",
                    "processingTime_ar" => "٧-١٠ أيام عمل",
                    "processingTime_zh" => "7-10个工作日",
                    "costPerPerson" => 949,
                    "description_en" => "Austria Schengen visas require passport, photo, travel insurance, hotel booking and proof of finances.",
                    "description_ar" => "تتطلب تأشيرات شنغن للنمسا جواز سفر، صورة شخصية، تأمين سفر، حجز فندق وإثبات مالي.",
                    "description_zh" => "奥地利申根签证需要护照、照片、旅行保险、酒店预订和资金证明。",
                ],
            ],
        ];

        $defaultDocuments = [
            "en" => [
                "Passport copy with at least 6 months validity.",
                "2 recent passport-size photographs with white background.",
                "Proof of accommodation or hotel booking.",
                "Return flight reservation or travel itinerary.",
                "Bank statement for the last 3 months.",
                "Valid travel medical insurance when required.",
                "Marriage certificate if traveling with spouse or children.",
            ],
            "ar" => [
                "نسخة من جواز السفر ساري المفعول لمدة ٦ أشهر على الأقل.",
                "صورتان شخصيتان حديثتان مقاس جواز السفر بخلفية بيضاء.",
                "إثبات الإقامة أو حجز فندق.",
                "حجز رحلة العودة أو خط سير الرحلة.",
                "كشف حساب بنكي لآخر ٣ أشهر.",
                "تأمين سفر طبي ساري المفعول عند الحاجة.",
                "شهادة الزواج إذا كان السفر مع الزوج أو الأطفال.",
            ],
            "zh" => [
                "有效期至少6个月的护照复印件。",
                "2张白色背景的近期护照尺寸照片。",
                "住宿证明或酒店预订。",
                "返程机票预订或旅行行程单。",
                "最近3个月的银行对账单。",
                "有效旅行医疗保险（如需要）。",
                "与配偶或子女一起旅行时的结婚证。",
            ],
        ];

        $defaultNotes = [
            "en" => [
                "Visa processing times and document requirements vary by country.",
                "Fees shown are an estimate and may change depending on the embassy.",
                "Some countries require an in-person appointment or biometric capture.",
                "Tilalr will contact you if any additional documents are needed.",
            ],
            "ar" => [
                "تختلف أوقات معالجة التأشيرات ومتطلبات المستندات حسب البلد.",
                "الرسوم الموضحة هي تقديرية وقد تتغير حسب السفارة.",
                "تتطلب بعض البلدان موعدًا شخصيًا أو بصمة حيوية.",
                "سيتواصل معكم تلالر إذا كانت هناك حاجة إلى أي مستندات إضافية.",
            ],
            "zh" => [
                "签证处理时间和文件要求因国家而异。",
                "所示费用为估算值，可能因大使馆而异。",
                "一些国家需要亲自预约或采集生物识别信息。",
                "如果需要任何额外文件，Tilalr将与您联系。",
            ],
        ];

        foreach ($countries as $country) {
            VisaCountry::create([
                'name_en' => $country['name_en'],
                'name_ar' => $country['name_ar'],
                'name_zh' => $country['name_zh'],
                'slug' => $country['slug'],
                'flag_emoji' => $country['flagEmoji'] ?? null,
                'flag_path' => $country['flagPath'] ?? null,
                'visa_type_en' => $country['visaInfo']['visaType_en'],
                'visa_type_ar' => $country['visaInfo']['visaType_ar'],
                'visa_type_zh' => $country['visaInfo']['visaType_zh'],
                'processing_time_en' => $country['visaInfo']['processingTime_en'],
                'processing_time_ar' => $country['visaInfo']['processingTime_ar'],
                'processing_time_zh' => $country['visaInfo']['processingTime_zh'],
                'cost_per_person' => $country['visaInfo']['costPerPerson'] ?? 949,
                'description_en' => $country['visaInfo']['description_en'],
                'description_ar' => $country['visaInfo']['description_ar'],
                'description_zh' => $country['visaInfo']['description_zh'],
                'documents' => $defaultDocuments,
                'notes' => $defaultNotes,
                'is_active' => true,
                'sort_order' => 0,
            ]);
        }
    }
}
