<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\IslandDestination;
use App\Models\City;

class IslandDestinationsSeeder extends Seeder
{
    public function run()
    {
        $internationals = [
            ['title_en' => 'Maldives Paradise Island', 'title_ar' => 'جزيرة المالديف الفردوس', 'title_zh' => '马尔代夫天堂岛', 'description_en' => 'Experience luxury at its finest with crystal clear waters and pristine beaches.', 'description_ar' => 'اختبر الفخامة بأفضل صورها مع المياه الصافية والشواطئ النقية.', 'description_zh' => '体验极致奢华，尽享清澈海水和原始海滩。', 'slug' => 'maldives-paradise', 'price' => 2500.00, 'rating' => 4.8, 'type' => 'international', 'image' => 'international/1.webp', 'duration_en' => '7 Days', 'duration_ar' => '٧ أيام', 'duration_zh' => '7天', 'groupSize_en' => '2-4 People', 'groupSize_ar' => '٢-٤ أشخاص', 'groupSize_zh' => '2-4人', 'location_en' => 'Maldives', 'location_ar' => 'المالديف', 'location_zh' => '马尔代夫', 'features' => json_encode(['Water Sports', 'Spa & Wellness', 'Fine Dining', 'Snorkeling']), 'features_ar' => json_encode(['رياضات مائية', 'سبا وعافية', 'تناول طعام فاخر', 'غطس']), 'features_zh' => json_encode(['水上运动', '水疗养生', '高级餐饮', '浮潜']), 'active' => true],
            ['title_en' => 'Bali Island Escape', 'title_ar' => 'رحلة جزيرة بالي', 'title_zh' => '巴厘岛逃离之旅', 'description_en' => 'Discover the cultural richness and natural beauty of Bali with expert guides.', 'description_ar' => 'اكتشف الثروة الثقافية والجمال الطبيعي لبالي مع الأدلاء الخبراء.', 'description_zh' => '与专业导游一起探索巴厘岛的文化底蕴和自然美景。', 'slug' => 'bali-escape', 'price' => 1800.00, 'rating' => 4.7, 'type' => 'international', 'image' => 'international/2.webp', 'duration_en' => '5 Days', 'duration_ar' => '٥ أيام', 'duration_zh' => '5天', 'groupSize_en' => '2-6 People', 'groupSize_ar' => '٢-٦ أشخاص', 'groupSize_zh' => '2-6人', 'location_en' => 'Indonesia', 'location_ar' => 'إندونيسيا', 'location_zh' => '印度尼西亚', 'features' => json_encode(['Temple Tours', 'Yoga Retreat', 'Beach Club', 'Cultural Immersion']), 'features_ar' => json_encode(['جولات معابد', 'انسحاب يوجا', 'ناد شاطئي', 'الانغماس الثقافي']), 'features_zh' => json_encode(['寺庙之旅', '瑜伽静修', '海滩俱乐部', '文化沉浸']), 'active' => true],
            ['title_en' => 'Seychelles Luxury Retreat', 'title_ar' => 'ملجأ سيشل الفاخر', 'title_zh' => '塞舌尔豪华度假', 'description_en' => 'An exclusive tropical paradise with white sand beaches and turquoise lagoons.', 'description_ar' => 'جنة استوائية حصرية مع شواطئ رملية بيضاء وبحيرات فيروزية.', 'description_zh' => '独享热带天堂，白沙海滩和碧绿泻湖。', 'slug' => 'seychelles-luxury', 'price' => 3200.00, 'rating' => 4.9, 'type' => 'international', 'image' => 'international/3.webp', 'duration_en' => '8 Days', 'duration_ar' => '٨ أيام', 'duration_zh' => '8天', 'groupSize_en' => '2-4 People', 'groupSize_ar' => '٢-٤ أشخاص', 'groupSize_zh' => '2-4人', 'location_en' => 'Seychelles', 'location_ar' => 'سيشل', 'location_zh' => '塞舌尔', 'features' => json_encode(['Diving', 'Private Beach', 'Sunset Cruises', 'Wildlife Tours']), 'features_ar' => json_encode(['غوص', 'شاطئ خاص', 'رحلات الغروب', 'جولات الحياة البرية']), 'features_zh' => json_encode(['潜水', '私人海滩', '日落巡航', '野生动物之旅']), 'active' => true],
            ['title_en' => 'Fiji Island Adventure', 'title_ar' => 'مغامرة جزر فيجي', 'title_zh' => '斐济岛冒险', 'description_en' => 'Adventure and relaxation in tropical Fiji islands.', 'description_ar' => 'المغامرة والاسترخاء في جزر فيجي الاستوائية.', 'description_zh' => '热带斐济岛屿的冒险和放松。', 'slug' => 'fiji-adventure', 'price' => 2200.00, 'rating' => 4.6, 'type' => 'international', 'image' => 'international/4.webp', 'duration_en' => '6 Days', 'duration_ar' => '٦ أيام', 'duration_zh' => '6天', 'groupSize_en' => '2-5 People', 'groupSize_ar' => '٢-٥ أشخاص', 'groupSize_zh' => '2-5人', 'location_en' => 'Fiji', 'location_ar' => 'فيجي', 'location_zh' => '斐济', 'features' => json_encode(['Beach Resorts', 'Water Sports', 'Island Tours', 'Relaxation']), 'features_ar' => json_encode(['منتجعات شاطئية', 'رياضات مائية', 'جولات جزيرة', 'استرخاء']), 'features_zh' => json_encode(['海滩度假村', '水上运动', '岛屿之旅', '放松']), 'active' => true],
            ['title_en' => 'Hawaii Tropical Paradise', 'title_ar' => 'جنة هاواي الاستوائية', 'title_zh' => '夏威夷热带天堂', 'description_en' => 'Stunning beaches and volcanic landscapes in Hawaii.', 'description_ar' => 'شواطئ خلابة ومناظر بركانية في هاواي.', 'description_zh' => '夏威夷的壮观海滩和火山景观。', 'slug' => 'hawaii-paradise', 'price' => 3000.00, 'rating' => 4.8, 'type' => 'international', 'image' => 'international/5.webp', 'duration_en' => '7 Days', 'duration_ar' => '٧ أيام', 'duration_zh' => '7天', 'groupSize_en' => '2-6 People', 'groupSize_ar' => '٢-٦ أشخاص', 'groupSize_zh' => '2-6人', 'location_en' => 'Hawaii', 'location_ar' => 'هاواي', 'location_zh' => '夏威夷', 'features' => json_encode(['Volcanic Tours', 'Beach Resorts', 'Surfing', 'Snorkeling']), 'features_ar' => json_encode(['جولات بركانية', 'منتجعات شاطئية', 'ركوب الأمواج', 'الغطس']), 'features_zh' => json_encode(['火山之旅', '海滩度假村', '冲浪', '浮潜']), 'active' => true],
            ['title_en' => 'Thailand Beach Getaway', 'title_ar' => 'رحلة شاطئ تايلاند', 'title_zh' => '泰国海滩度假', 'description_en' => 'Experience Thai culture and beautiful beaches.', 'description_ar' => 'اختبر الثقافة التايلاندية والشواطئ الجميلة.', 'description_zh' => '体验泰国文化和美丽的海滩。', 'slug' => 'thailand-getaway', 'price' => 1600.00, 'rating' => 4.7, 'type' => 'international', 'image' => 'international/6.webp', 'duration_en' => '5 Days', 'duration_ar' => '٥ أيام', 'duration_zh' => '5天', 'groupSize_en' => '2-8 People', 'groupSize_ar' => '٢-٨ أشخاص', 'groupSize_zh' => '2-8人', 'location_en' => 'Thailand', 'location_ar' => 'تايلاند', 'location_zh' => '泰国', 'features' => json_encode(['Temple Tours', 'Beach Resorts', 'Local Cuisine', 'Island Hopping']), 'features_ar' => json_encode(['جولات المعابد', 'منتجعات شاطئية', 'المطبخ المحلي', 'القفز بين الجزر']), 'features_zh' => json_encode(['寺庙之旅', '海滩度假村', '当地美食', '岛屿跳跃']), 'active' => true],
            ['title_en' => 'Mauritius Escape', 'title_ar' => 'رحلة موريشيوس', 'title_zh' => '毛里求斯逃离', 'description_en' => 'Pristine beaches and cultural diversity in Mauritius.', 'description_ar' => 'شواطئ نقية وتنوع ثقافي في موريشيوس.', 'description_zh' => '毛里求斯的原始海滩和文化多样性。', 'slug' => 'mauritius-escape', 'price' => 2400.00, 'rating' => 4.7, 'type' => 'international', 'image' => 'international/7.webp', 'duration_en' => '6 Days', 'duration_ar' => '٦ أيام', 'duration_zh' => '6天', 'groupSize_en' => '2-4 People', 'groupSize_ar' => '٢-٤ أشخاص', 'groupSize_zh' => '2-4人', 'location_en' => 'Mauritius', 'location_ar' => 'موريشيوس', 'location_zh' => '毛里求斯', 'features' => json_encode(['Beach Resorts', 'Water Sports', 'Cultural Tours', 'Fine Dining']), 'features_ar' => json_encode(['منتجعات شاطئية', 'رياضات مائية', 'جولات ثقافية', 'تناول طعام فاخر']), 'features_zh' => json_encode(['海滩度假村', '水上运动', '文化之旅', '高级餐饮']), 'active' => true],
            ['title_en' => 'Bora Bora Island Tour', 'title_ar' => 'جولة جزيرة بورا بورا', 'title_zh' => '波拉波拉岛之旅', 'description_en' => 'Overwater bungalows and crystal clear lagoons.', 'description_ar' => 'أكواخ فوق الماء وبحيرات صافية.', 'description_zh' => '水上小屋和清澈的泻湖。', 'slug' => 'bora-bora-tour', 'price' => 3500.00, 'rating' => 4.9, 'type' => 'international', 'image' => 'international/8.webp', 'duration_en' => '7 Days', 'duration_ar' => '٧ أيام', 'duration_zh' => '7天', 'groupSize_en' => '2-4 People', 'groupSize_ar' => '٢-٤ أشخاص', 'groupSize_zh' => '2-4人', 'location_en' => 'French Polynesia', 'location_ar' => 'بولينيزيا الفرنسية', 'location_zh' => '法属波利尼西亚', 'features' => json_encode(['Overwater Bungalows', 'Lagoon Activities', 'Snorkeling', 'Romance']), 'features_ar' => json_encode(['أكواخ فوق الماء', 'أنشطة البحيرة', 'الغطس', 'رومانسية']), 'features_zh' => json_encode(['水上别墅', '泻湖活动', '浮潜', '浪漫']), 'active' => true],
            ['title_en' => 'Caribbean Cruise Dream', 'title_ar' => 'رحلة حلم البحر الكاريبي', 'title_zh' => '加勒比海邮轮梦想', 'description_en' => 'Island hopping adventure in the Caribbean.', 'description_ar' => 'مغامرة القفز بين الجزر في البحر الكاريبي.', 'description_zh' => '加勒比海的岛屿跳跃冒险。', 'slug' => 'caribbean-cruise', 'price' => 2800.00, 'rating' => 4.6, 'type' => 'international', 'image' => 'international/9.webp', 'duration_en' => '8 Days', 'duration_ar' => '٨ أيام', 'duration_zh' => '8天', 'groupSize_en' => '4-10 People', 'groupSize_ar' => '٤-١٠ أشخاص', 'groupSize_zh' => '4-10人', 'location_en' => 'Caribbean', 'location_ar' => 'البحر الكاريبي', 'location_zh' => '加勒比海', 'features' => json_encode(['Island Hopping', 'Beach Resorts', 'Water Sports', 'Cruise']), 'features_ar' => json_encode(['القفز بين الجزر', 'منتجعات شاطئية', 'رياضات مائية', 'رحلة بحرية']), 'features_zh' => json_encode(['岛屿跳跃', '海滩度假村', '水上运动', '邮轮']), 'active' => true],
            ['title_en' => 'Palau Island Discovery', 'title_ar' => 'اكتشاف جزيرة بالاو', 'title_zh' => '帕劳岛发现', 'description_en' => 'World-class diving and pristine marine life.', 'description_ar' => 'الغوص من الدرجة الأولى والحياة البحرية النقية.', 'description_zh' => '世界级潜水和原始海洋生物。', 'slug' => 'palau-discovery', 'price' => 2600.00, 'rating' => 4.8, 'type' => 'international', 'image' => 'international/10.webp', 'duration_en' => '6 Days', 'duration_ar' => '٦ أيام', 'duration_zh' => '6天', 'groupSize_en' => '2-6 People', 'groupSize_ar' => '٢-٦ أشخاص', 'groupSize_zh' => '2-6人', 'location_en' => 'Palau', 'location_ar' => 'بالاو', 'location_zh' => '帕劳', 'features' => json_encode(['World-Class Diving', 'Jellyfish Lake', 'Marine Life', 'Adventures']), 'features_ar' => json_encode(['الغطس من الدرجة الأولى', 'بحيرة قنديل البحر', 'الحياة البحرية', 'المغامرات']), 'features_zh' => json_encode(['世界级潜水', '水母湖', '海洋生物', '冒险']), 'active' => true],
            ['title_en' => 'Santorini Greece Escape', 'title_ar' => 'رحلة سانتوريني اليونان', 'title_zh' => '圣托里尼希腊逃离', 'description_en' => 'White-washed buildings and stunning Mediterranean views.', 'description_ar' => 'مباني بيضاء ومناظر متوسطة خلابة.', 'description_zh' => '白色建筑和壮观的地中海景观。', 'slug' => 'santorini-escape', 'price' => 2000.00, 'rating' => 4.9, 'type' => 'international', 'image' => 'international/11.webp', 'duration_en' => '5 Days', 'duration_ar' => '٥ أيام', 'duration_zh' => '5天', 'groupSize_en' => '2-4 People', 'groupSize_ar' => '٢-٤ أشخاص', 'groupSize_zh' => '2-4人', 'location_en' => 'Greece', 'location_ar' => 'اليونان', 'location_zh' => '希腊', 'features' => json_encode(['Romantic Views', 'Beach Resorts', 'Local Wine', 'Sunset Views']), 'features_ar' => json_encode(['وجهات رومانسية', 'منتجعات شاطئية', 'النبيذ المحلي', 'مناظر الغروب']), 'features_zh' => json_encode(['浪漫景观', '海滩度假村', '当地葡萄酒', '日落景观']), 'active' => true],
            ['title_en' => 'Maldives Water Bungalow', 'title_ar' => 'أكواخ المالديف المائية', 'title_zh' => '马尔代夫水上小屋', 'description_en' => 'Exclusive water villas and underwater dining.', 'description_ar' => 'فيلات مائية حصرية وتناول طعام تحت الماء.', 'description_zh' => '独家水上别墅和水下餐饮。', 'slug' => 'maldives-bungalow', 'price' => 4000.00, 'rating' => 5.0, 'type' => 'international', 'image' => 'international/12.webp', 'duration_en' => '7 Days', 'duration_ar' => '٧ أيام', 'duration_zh' => '7天', 'groupSize_en' => '2-3 People', 'groupSize_ar' => '٢-٣ أشخاص', 'groupSize_zh' => '2-3人', 'location_en' => 'Maldives', 'location_ar' => 'المالديف', 'location_zh' => '马尔代夫', 'features' => json_encode(['Water Villas', 'Underwater Dining', 'Luxury', 'Exclusive']), 'features_ar' => json_encode(['فيلات مائية', 'مطاعم تحت الماء', 'الفخامة', 'حصري']), 'features_zh' => json_encode(['水上别墅', '水下餐饮', '豪华', '独家']), 'active' => true],
            ['title_en' => 'Maldives Resort Retreat', 'title_ar' => 'ملجأ منتجع المالديف', 'title_zh' => '马尔代夫度假村避暑', 'description_en' => 'All-inclusive tropical island resort experience.', 'description_ar' => 'تجربة منتجع جزيرة استوائية شاملة.', 'description_zh' => '包罗万象的热带岛屿度假村体验。', 'slug' => 'maldives-resort', 'price' => 2700.00, 'rating' => 4.8, 'type' => 'international', 'image' => 'international/13.webp', 'duration_en' => '6 Days', 'duration_ar' => '٦ أيام', 'duration_zh' => '6天', 'groupSize_en' => '2-8 People', 'groupSize_ar' => '٢-٨ أشخاص', 'groupSize_zh' => '2-8人', 'location_en' => 'Maldives', 'location_ar' => 'المالديف', 'location_zh' => '马尔代夫', 'features' => json_encode(['All-Inclusive', 'Beach Resorts', 'Water Sports', 'Dining']), 'features_ar' => json_encode(['شامل الكل', 'منتجعات شاطئية', 'رياضات مائية', 'المطاعم']), 'features_zh' => json_encode(['全包', '海滩度假村', '水上运动', '餐饮']), 'active' => true],
            ['title_en' => 'Bali Beach Bliss', 'title_ar' => 'نعيم شاطئ بالي', 'title_zh' => '巴厘岛海滩逍遥', 'description_en' => 'Tropical beaches and ancient temple exploration.', 'description_ar' => 'شواطئ استوائية واستكشاف المعابد القديمة.', 'description_zh' => '热带海滩和古庙探索。', 'slug' => 'bali-bliss', 'price' => 1500.00, 'rating' => 4.6, 'type' => 'international', 'image' => 'international/14.webp', 'duration_en' => '5 Days', 'duration_ar' => '٥ أيام', 'duration_zh' => '5天', 'groupSize_en' => '2-6 People', 'groupSize_ar' => '٢-٦ أشخاص', 'groupSize_zh' => '2-6人', 'location_en' => 'Indonesia', 'location_ar' => 'إندونيسيا', 'location_zh' => '印度尼西亚', 'features' => json_encode(['Temple Tours', 'Beach Resorts', 'Local Culture', 'Yoga']), 'features_ar' => json_encode(['جولات المعابد', 'منتجعات شاطئية', 'الثقافة المحلية', 'اليوجا']), 'features_zh' => json_encode(['寺庙之旅', '海滩度假村', '当地文化', '瑜伽']), 'active' => true],
            ['title_en' => 'Aruba Island Adventure', 'title_ar' => 'مغامرة جزيرة أروبا', 'title_zh' => '阿鲁巴岛冒险', 'description_en' => 'Sunny beaches and water sports paradise.', 'description_ar' => 'شواطئ مشمسة وجنة الألعاب المائية.', 'description_zh' => '阳光沙滩和水上运动天堂。', 'slug' => 'aruba-adventure', 'price' => 1900.00, 'rating' => 4.7, 'type' => 'international', 'image' => 'international/15.webp', 'duration_en' => '5 Days', 'duration_ar' => '٥ أيام', 'duration_zh' => '5天', 'groupSize_en' => '2-6 People', 'groupSize_ar' => '٢-٦ أشخاص', 'groupSize_zh' => '2-6人', 'location_en' => 'Aruba', 'location_ar' => 'أروبا', 'location_zh' => '阿鲁巴', 'features' => json_encode(['Sunny Beaches', 'Water Sports', 'Windsurfing', 'Relaxation']), 'features_ar' => json_encode(['شواطئ مشمسة', 'رياضات مائية', 'ركوب الأمواج', 'استرخاء']), 'features_zh' => json_encode(['阳光海滩', '水上运动', '风帆冲浪', '放松']), 'active' => true],
            ['title_en' => 'Zanzibar Spice Island', 'title_ar' => 'جزيرة زنجبار الفاخرة', 'title_zh' => '桑给巴尔香料岛', 'description_en' => 'Historic spice island with swahili culture.', 'description_ar' => 'جزيرة تاريخية بثقافة سواحيلية.', 'description_zh' => '具有斯瓦希里文化的历史香料岛。', 'slug' => 'zanzibar-spice', 'price' => 2100.00, 'rating' => 4.5, 'type' => 'international', 'image' => 'international/16.webp', 'duration_en' => '6 Days', 'duration_ar' => '٦ أيام', 'duration_zh' => '6天', 'groupSize_en' => '2-5 People', 'groupSize_ar' => '٢-٥ أشخاص', 'groupSize_zh' => '2-5人', 'location_en' => 'Tanzania', 'location_ar' => 'تنزانيا', 'location_zh' => '坦桑尼亚', 'features' => json_encode(['Historic Sites', 'Beach Resorts', 'Local Culture', 'Spice Tours']), 'features_ar' => json_encode(['مواقع تاريخية', 'منتجعات شاطئية', 'الثقافة المحلية', 'جولات التوابل']), 'features_zh' => json_encode(['历史遗迹', '海滩度假村', '当地文化', '香料之旅']), 'active' => true],
        ];

        foreach ($internationals as $data) {
            $attributes = ['slug' => $data['slug']];
            IslandDestination::updateOrCreate($attributes, $data);
        }
    }
}
